### ISSUE TITLE
Lita is pretty far ahead now.

### ISSUE THREAD

**Issue by jjasghar** [PatrickTulskie/lita-ping#2]
```
5:26:46 lita > (master) bundle
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Bundler could not find compatible versions for gem "lita":
  In Gemfile:
    lita-ping (>= 0) ruby depends on
      lita (~> 2.0) ruby

    lita (4.3.1)
15:30:59 lita > (master)
```

**Comment by PatrickTulskie** [comment]
Indeed. I haven't really updated anything for later versions of Lita. I'm open to pull reqs if you want to do it though.

**Comment by jjasghar** [comment]
Yeah i might take it on my shoulders, if I do i'll push up a PR.

**Comment by jjasghar** [comment]
I've pushed up: https://github.com/PatrickTulskie/lita-ping/pull/3

If you'll give me commit/rubygem access i can get this pushed up really quickly :)
